site_name: 'Python-App'
site_description: 'Main documentation for python-app features and framework APIs'
repo_url: https://github.com/OBILOTITI22/python-app
edit_uri: edit/master/docs

plugins:
  - techdocs-core
  - redirects:
      redirect_maps:
        'index.md': 'overview/what-is-backstage.md'

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.js`
nav:
  - Overview:
      - What is Python-app?: 'docs/index.md'
