name: ci

on:
  push:
    branches: [ master ]
    paths:
      - "src/**"
      # - "Dockerfile"
      # - ".github/workflows/ci.yaml"
  pull_request:
    branches: [ master ]
  workflow_dispatch: {}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true







          
          tags: obilotiti/python-app:${{ github.sha }}
